### ISSUE TITLE
[Bug] HP is incorrect

### ISSUE THREAD

**Issue by thatbudakguy** [alchemyrpg/ddb2alchemy#43]
### What happened?

reported by Murphy.D in discord.

### D&D Beyond Character Link

www.dndbeyond.com/characters/107095217/oLjOcg (404 on 2023-09-28, unfortunately)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkJPerry** [comment]
The code on Alchemy is out of date with the "main" branch on this repo. An update to the latest version of the code is in progress and this bug should be resolved by that update.

**Comment by ioveracker** [comment]
I'll put together a release and pull that into Alchemy right now so we can verify.

**Comment by ioveracker** [comment]
It looks like the issue with max HP is still happening, but it's on the Alchemy side of things. We started using trackers for HP some time ago and didn't update the import code. We're on it!

**Comment by ioveracker** [comment]
PR to convert HP and XP to trackers is open on the Alchemy side of things. Will report back after we've reviewed and deployed.

**Comment by ioveracker** [comment]
Alright, this issue is fixed in Alchemy now, which is also on v0.1.7 of this library.
